services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env.docker
    environment:
      - ENV_FILE=.env.docker
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: qa_db
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume: